# Generated by Django 5.0.1 on 2024-01-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='about_us',
            field=models.TextField(blank=True, null=True, verbose_name='about us'),
        ),
    ]
