# Generated by Django 5.0.1 on 2024-01-10 11:25

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_alter_createat_create_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLater',
            fields=[
                ('createat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.createat')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'News Later',
                'verbose_name_plural': 'News Later',
                'db_table': 'doctor_news_later',
            },
            bases=('common.createat',),
        ),
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('createat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.createat')),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='blog.categoryblog')),
            ],
            options={
                'verbose_name': 'category blog',
                'verbose_name_plural': 'category blog',
                'db_table': 'category_blog',
            },
            bases=('common.createat', models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('createat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.createat')),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=254, unique=True, verbose_name='Title')),
                ('short_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='short description')),
                ('slug', models.SlugField(allow_unicode=True, max_length=254, unique=True)),
                ('image', models.ImageField(upload_to='blog/%Y/%M/%d', verbose_name='Image')),
                ('width_image', models.PositiveIntegerField(blank=True, null=True)),
                ('height_image', models.PositiveIntegerField(blank=True, null=True)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(related_name='category_post', to='blog.categoryblog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'posts',
                'verbose_name_plural': 'posts',
                'ordering': ('-create_at',),
            },
            bases=('common.createat', models.Model),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('createat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.createat')),
                ('body', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_comments', to='blog.post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comment',
            },
            bases=('common.createat',),
        ),
    ]
