# Generated by Django 5.0.1 on 2024-01-17 15:01

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'News Later',
                'verbose_name_plural': 'News Later',
                'db_table': 'doctor_news_later',
            },
        ),
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='blog.categoryblog')),
            ],
            options={
                'verbose_name': 'category blog',
                'verbose_name_plural': 'category blog',
                'db_table': 'category_blog',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=254, unique=True, verbose_name='Title')),
                ('en_title', models.CharField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid characters', message='please enter unicode characters', regex='^[a-zA-Z\\-\\_\\s]+$'), django.core.validators.MinLengthValidator(20)], verbose_name='en Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=254, unique=True)),
                ('image', models.ImageField(upload_to='blog/%Y/%M/%d', verbose_name='Image')),
                ('width_image', models.PositiveIntegerField(blank=True, null=True)),
                ('height_image', models.PositiveIntegerField(blank=True, null=True)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(related_name='category_post', to='blog.categoryblog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'posts',
                'verbose_name_plural': 'posts',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('body', models.TextField(verbose_name='text comment')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت کامنت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_comment', to='blog.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comment',
                'ordering': ('-create_at',),
            },
        ),
    ]
