# Generated by Django 5.0.1 on 2024-01-09 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('createat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.createat')),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='blog.categoryblog')),
            ],
            options={
                'verbose_name': 'category blog',
                'verbose_name_plural': 'category blog',
                'db_table': 'category_blog',
            },
            bases=('common.createat', models.Model),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='category_post', to='blog.categoryblog'),
            preserve_default=False,
        ),
    ]
