# Generated by Django 5.0.1 on 2024-01-10 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoryblog_level_categoryblog_lft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryblog',
            name='level',
        ),
        migrations.RemoveField(
            model_name='categoryblog',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='categoryblog',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='categoryblog',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='categoryblog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='blog.categoryblog'),
        ),
    ]
