# Generated by Django 5.0.1 on 2024-01-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='short description'),
        ),
    ]
