# Generated by Django 5.0.1 on 2024-01-10 06:34

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-create_at',), 'verbose_name': 'posts', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterField(
            model_name='categoryblog',
            name='update_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
    ]
