# Generated by Django 5.0.1 on 2024-01-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_parent_alter_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('published', 'Publish'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='draft', max_length=9, verbose_name='Status'),
        ),
    ]
