# Generated by Django 5.0.1 on 2024-01-12 12:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_options_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='en_title',
            field=models.CharField(default=0, max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid characters', message='please enter unicode characters', regex='^[\\w\\s\\d\\-]+$')], verbose_name='en Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.post'),
        ),
    ]
