# Generated by Django 5.0.1 on 2024-01-12 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_en_title_alter_comment_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='en_title',
            field=models.CharField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid characters', message='please enter unicode characters', regex='^[a-zA-Z\\-\\_]+$')], verbose_name='en Title'),
        ),
    ]
