# Generated by Django 5.0.1 on 2024-01-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_en_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short_description',
        ),
    ]
