# Generated by Django 5.0.1 on 2024-01-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('createat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.createat')),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about-us/%Y/%M/%d', verbose_name='image')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
                'db_table': 'about-us',
            },
            bases=('common.createat', models.Model),
        ),
    ]
