# Generated by Django 5.0.1 on 2024-01-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sciolaboutus',
            name='url',
            field=models.URLField(max_length=254, verbose_name='sciol name url'),
        ),
    ]
