# Generated by Django 5.0.1 on 2024-01-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
