# Generated by Django 5.0.1 on 2024-01-09 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('sites', '0003_aboutus_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SciolAboutUs',
            fields=[
                ('createat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.createat')),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.URLField(max_length=254, verbose_name='sciol name')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'sciol',
                'verbose_name_plural': 'sciol',
                'db_table': 'sciol-about-us',
            },
            bases=('common.createat', models.Model),
        ),
    ]
