# Generated by Django 5.0.1 on 2024-01-10 06:34

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_sciolaboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='update_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='permisionsite',
            name='update_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sciolaboutus',
            name='update_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
    ]
