# Generated by Django 5.0.1 on 2024-01-17 15:23

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAppointmentDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('update_at', django_jalali.db.models.jDateTimeField(auto_now=True, null=True)),
                ('from_time', django_jalali.db.models.jDateTimeField(unique=True, verbose_name='from time')),
                ('at_time', django_jalali.db.models.jDateTimeField(unique=True, verbose_name='at time')),
                ('price', models.PositiveIntegerField()),
                ('cancel_description', models.TextField(blank=True, null=True, verbose_name='cancel description')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_doctor_admin', to='doctor.doctor')),
            ],
            options={
                'verbose_name': 'card_appointment_doctor_admin',
                'verbose_name_plural': 'card_appointment_doctor_admin',
                'db_table': 'card_appointment_doctor_admin',
            },
        ),
    ]
