# Generated by Django 5.0.1 on 2024-01-10 06:34

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationphone',
            name='update_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='communications',
            name='update_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='update_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='update_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='update_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='skildoctor',
            name='update_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True),
        ),
    ]
