# Generated by Django 5.0.1 on 2024-01-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about_us_doctor',
            field=models.TextField(blank=True, null=True, verbose_name='about us doctor'),
        ),
    ]
