# Generated by Django 5.0.1 on 2024-01-17 13:46

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_date_shamsi',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Date of Shamsi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_birth_dat',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth milady'),
        ),
    ]
